### ISSUE TITLE
Can't npm start

### ISSUE THREAD

**Issue by chrislevn** [NEU-Skunkworks/C19_Website#8]
I got this error when running "npm start". Any ideas how I can fix this?

Logger Level On :  debug
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './.env/researcher_keys/private.key'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (C:\Users\locvi\Documents\GitHub\C19_Website\src\controller\volunteerController.js:19:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\locvi\Documents\GitHub\C19_Website\src\Routes\volunteerRoutes.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[nodemon] app crashed - waiting for file changes before starting...

**Comment by rahulh25** [comment]
You need to create the folders. I am updating the readme file with the latest steps that might be helpful.
